language: node_js

node_js:
  - 6

deploy:
  provider: npm
  email: paolo.scanferla@mondora.com
  api_key: $NPM_TOKEN
  on:
    tags: true

script:
  - npm run lint
  - npm run coverage
  - npm run coveralls
